/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * This file initialises the USB (tinyUSB) and USART (SERCOM). Board USART settings
 * are set in 'boards/<board>/mpconfigboard.h.
 *
 * IMPORTANT: Please refer to "I/O Multiplexing and Considerations" chapters
 *            in device datasheets for I/O Pin functions and assignments.
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Damien P. George
 * Copyright (c) 2022 Robert Hammelrath
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "py/runtime.h"
#include "modmachine.h"
#include "samd_soc.h"
#include "sam.h"
#include "tusb.h"
#include "mphalport.h"

/*
 * Clock overview:
 * The SAMD/SAML chips have a number of generic clocks (GCLK)
 * each of which can be generated from different inputs,
 * such as internal oscillators, PLLs, external crystals, etc.
 * The GCLK_MAIN is used for the synchronous CPU and the main buses,
 * while each of the GLCKn are used to async clock different peripherals
 * such as.
 *
 * TCn: Timer Counters. These are normally 16-bits, but can be combined
 * in pairs for 32-bit counters. Used for scheduling interrupts, etc.
 * TCCn: Timer Counters for Control: similar to TC, but with extra waveform
 * generation functions for PWM etc
 * RTC: Real time clock
 * 
 *
 * SAML22 has 5 GCLK channels, 4 TC peripherals, 1 TCC.
 * RTC: divided by 1024 => 32 Hz.
 * GCLK0: 8 MHz system clock
 * GCLK1: 48 Mhz USB clock (generated by PLL 32768Hz * 1465
 *
 * TC0: 781 Hz usb device callback
 * TC1: 156 Hz usb cdc callback
 * TC2/3: 32-bit microsecond counter
 */

extern void machine_rtc_start(bool force);

#define LED_RED GPIO(GPIO_PORTA, 21)
#define LED_GREEN GPIO(GPIO_PORTA, 20)
void led_set(int led, int value)
{
    gpio_set_pin_level(led ? LED_RED : LED_GREEN, value);
}
void led_green_toggle()
{
    static int state = 0;
    led_set(1, (state = !state));
}
void led_red_toggle()
{
    static int state = 0;
    led_set(0, (state = !state));
}

void led_init()
{
    gpio_set_pin_direction(LED_RED, GPIO_DIRECTION_OUT);
    gpio_set_pin_direction(LED_GREEN, GPIO_DIRECTION_OUT);
    led_set(0,0);
    led_set(1,0);
}

static void usb_init_saml22(void)
{
    led_init();

    // disable USB, just in case.
    hri_usb_clear_CTRLA_ENABLE_bit(USB);

    // bump clock up to 8 MHz
    hri_oscctrl_write_OSC16MCTRL_FSEL_bf(OSCCTRL, OSCCTRL_OSC16MCTRL_FSEL_8_Val);

    // reset flags and disable DFLL
    OSCCTRL->INTFLAG.reg = OSCCTRL_INTFLAG_DFLLRDY;
    OSCCTRL->DFLLCTRL.reg = 0;
    while (!(OSCCTRL->STATUS.reg & OSCCTRL_STATUS_DFLLRDY));

    // set the coarse and fine values to speed up frequency lock.
    uint32_t coarse =(*((uint32_t *)NVMCTRL_OTP5)) >> 26;
    OSCCTRL->DFLLVAL.reg = 0
	| OSCCTRL_DFLLVAL_COARSE(coarse)
	| OSCCTRL_DFLLVAL_FINE(0x200)
	;

    // set coarse and fine steps, and multiplier (48 MHz = 32768 Hz * 1465)
    OSCCTRL->DFLLMUL.reg = 0
	| OSCCTRL_DFLLMUL_CSTEP( 1 )
	| OSCCTRL_DFLLMUL_FSTEP( 1 )
	//| OSCCTRL_DFLLMUL_MUL( 1465 )
	| OSCCTRL_DFLLMUL_MUL( 48000000 / 32768 + 1 )
	;

    // set closed loop mode, chill cycle disable and USB clock recovery mode, and enable the DFLL.
    OSCCTRL->DFLLCTRL.reg = 0
	| OSCCTRL_DFLLCTRL_MODE
	| OSCCTRL_DFLLCTRL_CCDIS
	| OSCCTRL_DFLLCTRL_ONDEMAND
	| OSCCTRL_DFLLCTRL_RUNSTDBY
	| OSCCTRL_DFLLCTRL_USBCRM
	| OSCCTRL_DFLLCTRL_ENABLE
	;

    while (!(OSCCTRL->STATUS.reg & OSCCTRL_STATUS_DFLLRDY));

    // assign DFLL to GCLK1
    GCLK->GENCTRL[1].reg = 0
	| GCLK_GENCTRL_SRC(GCLK_GENCTRL_SRC_DFLL48M)
	| GCLK_GENCTRL_DIV(1)
	| GCLK_GENCTRL_GENEN
	// | GCLK_GENCTRL_OE
	;

    while (GCLK->SYNCBUSY.bit.GENCTRL1); // wait for generator control 1 to sync

    // assign GCLK1 to USB
    hri_gclk_write_PCHCTRL_reg(GCLK, USB_GCLK_ID, GCLK_PCHCTRL_GEN_GCLK1_Val | GCLK_PCHCTRL_CHEN);
    hri_mclk_set_AHBMASK_USB_bit(MCLK);
    hri_mclk_set_APBBMASK_USB_bit(MCLK);

    // USB Pin Init
    gpio_set_pin_direction(PIN_PA24, GPIO_DIRECTION_OUT);
    gpio_set_pin_level(PIN_PA24, false);
    gpio_set_pin_pull_mode(PIN_PA24, GPIO_PULL_OFF);
    gpio_set_pin_direction(PIN_PA25, GPIO_DIRECTION_OUT);
    gpio_set_pin_level(PIN_PA25, false);
    gpio_set_pin_pull_mode(PIN_PA25, GPIO_PULL_OFF);

    gpio_set_pin_function(PIN_PA24, PINMUX_PA24G_USB_DM);
    gpio_set_pin_function(PIN_PA25, PINMUX_PA25G_USB_DP);

    // the sensor watch enabled usb at this point and scheduled
    // call back timers:
    //_watch_enable_tc0();
    // tusb_init();
    //_watch_enable_tc1();

}


static void usb_init(void) {
    usb_init_saml22();

#if 0
    // Init USB clock
    #if defined(MCU_SAMD21)
    GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK5 | GCLK_CLKCTRL_ID_USB;
    PM->AHBMASK.bit.USB_ = 1;
    PM->APBBMASK.bit.USB_ = 1;
    uint8_t alt = 6; // alt G, USB

    // Init USB pins
    PORT->Group[0].DIRSET.reg = 1 << 25 | 1 << 24;
    PORT->Group[0].OUTCLR.reg = 1 << 25 | 1 << 24;
    PORT->Group[0].PMUX[12].reg = alt << 4 | alt;
    PORT->Group[0].PINCFG[24].reg = PORT_PINCFG_PMUXEN;
    PORT->Group[0].PINCFG[25].reg = PORT_PINCFG_PMUXEN;
    #elif defined(MCU_SAML22)
// todo: look at Sensor-Watch/watch-library/hardware/watch/watch_private.c
    // disable USB, just in case.
    hri_usb_clear_CTRLA_ENABLE_bit(USB);

    // bump clock up to 8 MHz
    hri_oscctrl_write_OSC16MCTRL_FSEL_bf(OSCCTRL, OSCCTRL_OSC16MCTRL_FSEL_8_Val);

    // reset flags and disable DFLL
    OSCCTRL->INTFLAG.reg = OSCCTRL_INTFLAG_DFLLRDY;
    OSCCTRL->DFLLCTRL.reg = 0;
    while (!(OSCCTRL->STATUS.reg & OSCCTRL_STATUS_DFLLRDY));

    // set the coarse and fine values to speed up frequency lock.
    uint32_t coarse =(*((uint32_t *)NVMCTRL_OTP5)) >> 26;
    OSCCTRL->DFLLVAL.reg = OSCCTRL_DFLLVAL_COARSE(coarse) |
                           OSCCTRL_DFLLVAL_FINE(0x200);
    // set coarse and fine steps, and multiplier (48 MHz = 32768 Hz * 1465)
    OSCCTRL->DFLLMUL.reg = OSCCTRL_DFLLMUL_CSTEP( 1 ) |
                           OSCCTRL_DFLLMUL_FSTEP( 1 ) |
                           OSCCTRL_DFLLMUL_MUL( 1465 );
    // set closed loop mode, chill cycle disable and USB clock recovery mode, and enable the DFLL.
    OSCCTRL->DFLLCTRL.reg = OSCCTRL_DFLLCTRL_MODE | OSCCTRL_DFLLCTRL_CCDIS | OSCCTRL_DFLLCTRL_ONDEMAND | OSCCTRL_DFLLCTRL_RUNSTDBY | OSCCTRL_DFLLCTRL_USBCRM | OSCCTRL_DFLLCTRL_ENABLE;
    while (!(OSCCTRL->STATUS.reg & OSCCTRL_STATUS_DFLLRDY));

    // assign DFLL to GCLK1
    GCLK->GENCTRL[1].reg = GCLK_GENCTRL_SRC(GCLK_GENCTRL_SRC_DFLL48M) | GCLK_GENCTRL_DIV(1) | GCLK_GENCTRL_GENEN;// | GCLK_GENCTRL_OE;
    while (GCLK->SYNCBUSY.bit.GENCTRL1); // wait for generator control 1 to sync

    // assign GCLK1 to USB
    hri_gclk_write_PCHCTRL_reg(GCLK, USB_GCLK_ID, GCLK_PCHCTRL_GEN_GCLK1_Val | GCLK_PCHCTRL_CHEN);
    hri_mclk_set_AHBMASK_USB_bit(MCLK);
    hri_mclk_set_APBBMASK_USB_bit(MCLK);


    // USB Pin Init
    gpio_set_pin_direction(PIN_PA24, GPIO_DIRECTION_OUT);
    gpio_set_pin_level(PIN_PA24, false);
    gpio_set_pin_pull_mode(PIN_PA24, GPIO_PULL_OFF);
    gpio_set_pin_direction(PIN_PA25, GPIO_DIRECTION_OUT);
    gpio_set_pin_level(PIN_PA25, false);
    gpio_set_pin_pull_mode(PIN_PA25, GPIO_PULL_OFF);

    gpio_set_pin_function(PIN_PA24, PINMUX_PA24G_USB_DM);
    gpio_set_pin_function(PIN_PA25, PINMUX_PA25G_USB_DP);

    _watch_enable_tc0();

    #endif

#endif
}

static void saml22_us_counter(void)
{
    // is this not required?
    //MCLK->APBCMASK.bit.TC2_ = 1; // Enable TC2 clock
    //MCLK->APBCMASK.bit.TC3_ = 1; // Enable TC3 clock

    hri_gclk_write_PCHCTRL_reg(GCLK, TC2_GCLK_ID, GCLK_PCHCTRL_GEN_GCLK0_Val | GCLK_PCHCTRL_CHEN);
    // and enable the peripheral clock.
    hri_mclk_set_APBCMASK_TC2_bit(MCLK);

    // disable and reset TC2.
    hri_tc_clear_CTRLA_ENABLE_bit(TC2);
    hri_tc_wait_for_sync(TC2, TC_SYNCBUSY_ENABLE);
    hri_tc_write_CTRLA_reg(TC2, TC_CTRLA_SWRST);
    hri_tc_wait_for_sync(TC2, TC_SYNCBUSY_SWRST);
    hri_tc_write_CTRLA_reg(TC2, 0
	| TC_CTRLA_PRESCALER_DIV8 // divide the 8 MHz clock by 8 to count 1 MHz
	| TC_CTRLA_MODE_COUNT32   // count in 32-bit mode (uses TC3 as well)
	| TC_CTRLA_RUNSTDBY       // run in standby, just in case we figure that out
    );
    // set an interrupt on overflow; this will call TC2_Handler below.
    hri_tc_set_INTEN_OVF_bit(TC2);

    // set priority higher than TC1
    NVIC_SetPriority(TC2_IRQn, 5);
    NVIC_ClearPendingIRQ(TC2_IRQn);
    NVIC_EnableIRQ(TC2_IRQn);

    // Start the timer
    hri_tc_set_CTRLA_ENABLE_bit(TC2);
}

/*
 * Initialize the 32-bit µs counter using pair of 16-bit counters
 * SAMD51: TC 0/1
 * SAMD21: TC 3/4
 * SAML22: TC 2/3 (TC4 does not support 32-bit, 34.6.2.4 Counter mode)
 */
void init_us_counter(void) {
    #if defined(MCU_SAMD21)

    PM->APBCMASK.bit.TC3_ = 1; // Enable TC3 clock
    PM->APBCMASK.bit.TC4_ = 1; // Enable TC4 clock
    // Select multiplexer generic clock source and enable.
    GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK3 | GCLK_CLKCTRL_ID_TC4_TC5;
    // Wait while it updates synchronously.
    while (GCLK->STATUS.bit.SYNCBUSY) {
    }

    // configure the timer
    TC4->COUNT32.CTRLA.bit.MODE = TC_CTRLA_MODE_COUNT32_Val;
    TC4->COUNT32.CTRLA.bit.RUNSTDBY = 1;
    TC4->COUNT32.CTRLA.bit.ENABLE = 1;
    while (TC4->COUNT32.STATUS.bit.SYNCBUSY) {
    }
    TC4->COUNT32.READREQ.reg = TC_READREQ_RREQ | TC_READREQ_RCONT | 0x10;
    while (TC4->COUNT32.STATUS.bit.SYNCBUSY) {
    }
    // Enable the IRQ
    TC4->COUNT32.INTENSET.reg = TC_INTENSET_OVF;
    NVIC_EnableIRQ(TC4_IRQn);

    #elif defined(MCU_SAML22)
    saml22_us_counter();
/*
    MCLK->APBCMASK.bit.TC2_ = 1; // Enable TC2 clock
    MCLK->APBCMASK.bit.TC3_ = 1; // Enable TC3 clock
    // Peripheral channel 9 is driven by GCLK0, 8 MHz.
    GCLK->PCHCTRL[TC2_GCLK_ID].reg = GCLK_PCHCTRL_GEN_GCLK0 | GCLK_PCHCTRL_CHEN;
    while (GCLK->PCHCTRL[TC2_GCLK_ID].bit.CHEN == 0) {
    }

    // configure the timer
    TC2->COUNT32.CTRLA.bit.PRESCALER = 3; // divide by 8 => microseconds
    TC2->COUNT32.CTRLA.bit.MODE = TC_CTRLA_MODE_COUNT32_Val;
    TC2->COUNT32.CTRLA.bit.RUNSTDBY = 1;
    TC2->COUNT32.CTRLA.bit.ENABLE = 1;
    while (TC2->COUNT32.SYNCBUSY.bit.ENABLE) {
    }

    // Enable the IRQ
    TC2->COUNT32.INTENSET.reg = TC_INTENSET_OVF;
    NVIC_EnableIRQ(TC2_IRQn);
*/
     #elif defined(MCU_SAMD51)

    MCLK->APBAMASK.bit.TC0_ = 1; // Enable TC0 clock
    MCLK->APBAMASK.bit.TC1_ = 1; // Enable TC1 clock
    // Peripheral channel 9 is driven by GCLK3, 8 MHz.
    GCLK->PCHCTRL[TC0_GCLK_ID].reg = GCLK_PCHCTRL_GEN_GCLK3 | GCLK_PCHCTRL_CHEN;
    while (GCLK->PCHCTRL[TC0_GCLK_ID].bit.CHEN == 0) {
    }

    // configure the timer
    TC0->COUNT32.CTRLA.bit.PRESCALER = 0;
    TC0->COUNT32.CTRLA.bit.MODE = TC_CTRLA_MODE_COUNT32_Val;
    TC0->COUNT32.CTRLA.bit.RUNSTDBY = 1;
    TC0->COUNT32.CTRLA.bit.ENABLE = 1;
    while (TC0->COUNT32.SYNCBUSY.bit.ENABLE) {
    }

    // Enable the IRQ
    TC0->COUNT32.INTENSET.reg = TC_INTENSET_OVF;
    NVIC_EnableIRQ(TC0_IRQn);
    #endif
}


void infinite_loop()
{
//#define LED_RED PIN_PA20
//#define LED_GREEN PIN_PA21
gpio_set_pin_direction(LED_RED, GPIO_DIRECTION_OUT);
//gpio_set_pin_function(LED_RED, 0);
gpio_set_pin_direction(LED_GREEN, GPIO_DIRECTION_OUT);
//gpio_set_pin_function(LED_GREEN, 0);

while(1)
{
	gpio_set_pin_level(LED_RED, 0);
	gpio_set_pin_level(LED_GREEN, 1);

	for(volatile int i = 0 ; i < 1000000/4 ; i++)
		;

	gpio_set_pin_level(LED_RED, 1);
	gpio_set_pin_level(LED_GREEN, 0);

	for(volatile int i = 0 ; i < 1000000/4 ; i++)
		;
}
}

void samd_init(void) {
    init_clocks(get_cpu_freq());
    init_us_counter();
    machine_rtc_start(false);
    usb_init();
    #if defined(MCU_SAMD51)
    mp_hal_ticks_cpu_enable();
    #endif
}

#if MICROPY_PY_MACHINE_I2C || MICROPY_PY_MACHINE_SPI || MICROPY_PY_MACHINE_UART

Sercom *sercom_instance[] = SERCOM_INSTS;
MP_REGISTER_ROOT_POINTER(void *sercom_table[SERCOM_INST_NUM]);

// Common Sercom functions used by all Serial devices
void sercom_enable(Sercom *uart, int state) {
    uart->USART.CTRLA.bit.ENABLE = state; // Set the state on/off
    // Wait for the Registers to update.
    while (uart->USART.SYNCBUSY.bit.ENABLE) {
    }
}

void sercom_deinit_all(void) {
    for (int i = 0; i < SERCOM_INST_NUM; i++) {
        Sercom *uart = sercom_instance[i];
        uart->USART.INTENCLR.reg = 0xff;
        sercom_register_irq(i, NULL);
        sercom_enable(uart, 0);
        MP_STATE_PORT(sercom_table[i]) = NULL;
    }
}

#endif

void samd_get_unique_id(samd_unique_id_t *id) {
    // Atmel SAM D21E / SAM D21G / SAM D21J
    // SMART ARM-Based Microcontroller
    // "Serial number" DATASHEET section
    // SAMD51: 9.6
    // SAMD21: 9.3.3 (or 10.3.3 depending on which manual)
    // SAML22: 9.5 (DS60001465D)
    //
    // EXAMPLE (SAMD21)
    // ----------------
    // OpenOCD:
    // Word0:
    // > at91samd21g18.cpu mdw 0x0080A00C 1
    // 0x0080a00c: 6e27f15f
    // Words 1-3:
    // > at91samd21g18.cpu mdw 0x0080A040 3
    // 0x0080a040: 50534b54 332e3120 ff091645
    //
    // MicroPython (this code and same order as shown in Arduino IDE)
    // >>> binascii.hexlify(machine.unique_id())
    // b'6e27f15f50534b54332e3120ff091645'

    #if defined(MCU_SAMD21) || defined(MCU_SAML22)
    uint32_t *id_addresses[4] = {(uint32_t *)0x0080A00C, (uint32_t *)0x0080A040,
                                 (uint32_t *)0x0080A044, (uint32_t *)0x0080A048};
    #elif defined(MCU_SAMD51)
    uint32_t *id_addresses[4] = {(uint32_t *)0x008061FC, (uint32_t *)0x00806010,
                                 (uint32_t *)0x00806014, (uint32_t *)0x00806018};
    #endif

    for (int i = 0; i < 4; i++) {
        for (int k = 0; k < 4; k++) {
            // 'Reverse' the read bytes into a 32 bit word (Consistent with Arduino)
            id->bytes[4 * i + k] = (*(id_addresses[i]) >> (24 - k * 8)) & 0xff;
        }
    }
}
